# Generated by Django 5.0.6 on 2024-05-22 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="coffee_varieties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="coffees/")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CAP", "Capachino"),
                            ("BC", "Black Coffee"),
                            ("CC", "Cold Coffee"),
                            ("EX", "Espresso"),
                            ("Pc", "Plane Coffee"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
