# Generated by Django 5.0.6 on 2024-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee_varieties",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
