# Generated by Django 5.0.6 on 2024-05-31 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0002_coffee_varieties_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="coff_certificates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                ("issed_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_till", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "coffee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.coffee_varieties",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="coffee_review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("rating", models.IntegerField(default=1)),
                ("review", models.TextField(default="")),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coffee.coffee_varieties",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store_Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "coff_varieties",
                    models.ManyToManyField(
                        related_name="stores", to="coffee.coffee_varieties"
                    ),
                ),
            ],
        ),
    ]
